<<<<<<< HEAD
# Generated by Django 6.0.5 on 2026-05-18 08:28
=======
# Generated by Django 6.0.5 on 2026-05-18 06:17
>>>>>>> ca0f6fb59a822831c9d04ef833229200fc22fc2e

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_code', models.CharField(max_length=3)),
                ('country_name', models.CharField(max_length=100)),
                ('iso', models.CharField(blank=True, max_length=3, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('default_time_zone', models.CharField(blank=True, max_length=50, null=True)),
                ('default_language', models.CharField(blank=True, max_length=20, null=True)),
                ('date_format', models.CharField(blank=True, max_length=20, null=True)),
                ('allow_asset_location', models.BooleanField(default=True)),
                ('default_country', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_code', models.CharField(blank=True, max_length=10, null=True)),
                ('branch_name', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('postal_code', models.IntegerField(blank=True, null=True)),
=======
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_dept_id', models.IntegerField(blank=True, null=True)),
                ('dept_code', models.CharField(blank=True, max_length=20, null=True)),
                ('dept_name', models.CharField(max_length=100)),
                ('dept_type', models.CharField(default='OPERATIONS', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_id', models.IntegerField()),
                ('location_code', models.CharField(max_length=10)),
                ('location_name', models.CharField(max_length=100)),
                ('location_type', models.CharField(choices=[('WAREHOUSE', 'Warehouse'), ('OFFICE', 'Office'), ('STORE', 'Store'), ('FACTORY', 'Factory'), ('BRANCH', 'Branch')], default='OFFICE', max_length=20)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('line1', models.CharField(blank=True, max_length=255, null=True)),
                ('line2', models.CharField(blank=True, max_length=255, null=True)),
                ('gps_map_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('full_location_code', models.CharField(blank=True, max_length=100)),
                ('full_path', models.TextField(blank=True)),
                ('allow_asset_assignment', models.BooleanField(default=True)),
>>>>>>> ca0f6fb59a822831c9d04ef833229200fc22fc2e
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
<<<<<<< HEAD
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='master_data.country')),
            ],
            options={
                'db_table': 'branch',
            },
=======
                ('parent_location', models.ForeignKey(blank=True, db_column='parent_location_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_locations', to='master_data.location')),
            ],
>>>>>>> ca0f6fb59a822831c9d04ef833229200fc22fc2e
        ),
    ]
